services:
  - type: web
    name: quizmaster
    runtime: docker
    envVars:
      - key: APP_KEY
        value: base64:JI1lz1T02QxYhbcGC7yNDy6WtvTltIUe5VSMcUXiB6w=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: DB_CONNECTION
        value: sqlite
